#ifndef TESTMSGPLUGIN_GLOBAL_H
#define TESTMSGPLUGIN_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TESTMSGPLUGIN_LIBRARY)
#  define TESTMSGPLUGIN_EXPORT Q_DECL_EXPORT
#else
#  define TESTMSGPLUGIN_EXPORT Q_DECL_IMPORT
#endif

#endif // TESTMSGPLUGIN_GLOBAL_H
